# JRE 17.0.7:
FROM docker.io/eclipse-temurin@sha256:7cbe01fd3d515407f1fda1e68068831aa6ae4b6930d76cdaa43736dc810bbd1b

ENV LANG="en_US.UTF-8" LANGUAGE="en_US:en"

USER 185
WORKDIR /deployment

COPY --chown=185 target/quarkus-app/lib/ /deployment/lib/
COPY --chown=185 target/quarkus-app/*.jar /deployment/
COPY --chown=185 target/quarkus-app/app/ /deployment/app/
COPY --chown=185 target/quarkus-app/quarkus/ /deployment/quarkus/

ENTRYPOINT [ "java", "-jar", "quarkus-run.jar" ]